routeEnhancers:
  GadgetoGoogleMap:
    type: Extbase
    namespace: 'tx_gadgetogoogle_map' # tx-prefix needed - whatever!
    routes:
      - routePath: '/map'
        _controller: 'Map::show'
    defaultController: 'Map::show'

  GadgetoGoogleList:
    type: Extbase
    namespace: 'tx_gadgetogoogle_list' # tx-prefix needed - whatever!
    routes:
      - routePath: '/location-list'
        _controller: 'Location::list'
    defaultController: 'Location::list'

  GadgetoGoogleDetail:
    type: Extbase
    namespace: 'tx_gadgetogoogle_detail'  # tx-prefix needed - whatever!
    routes:
      - routePath: '/location-detail/{location}'
        _controller: 'Location::detail'
      - routePath: '/location-detail-1/{location}/{prevLocation}'
        _controller: 'Location::detail'
      - routePath: '/location-detail-2/{location}/{nextLocation}'
        _controller: 'Location::detail'
      - routePath: '/location-detail/{location}/{prevLocation}/{nextLocation}'
        _controller: 'Location::detail'
    defaultController: 'Location::detail'
    requirements:
      location: '^[a-z0-9\-]+$'
      prevLocation: '[0-9]+'
      nextLocation: '[0-9]+'
    aspects:
      location:
        type: PersistedAliasMapper
        tableName: tx_gadgetogoogle_domain_model_location
        routeFieldName: slug

